2020-04-01 10:21:07,337 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 10:21:13,235 django.request WARNING  Not Found: /
2020-04-01 10:21:13,236 django.server WARNING  "GET / HTTP/1.1" 404 2143
2020-04-01 10:21:21,718 django.request WARNING  Not Found: /accounts/register
2020-04-01 10:21:21,718 django.server WARNING  "GET /accounts/register HTTP/1.1" 404 3678
2020-04-01 10:27:45,692 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 10:28:28,676 django.request WARNING  Not Found: /
2020-04-01 10:28:28,677 django.server WARNING  "GET / HTTP/1.1" 404 2252
2020-04-01 10:28:32,246 django.server INFO     "GET /register HTTP/1.1" 301 0
2020-04-01 10:28:32,345 django.request ERROR    Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\registration\views.py", line 54, in user_register
    return render(request, template, {'form': form})
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/registration.html
2020-04-01 10:28:32,348 django.server ERROR    "GET /register/ HTTP/1.1" 500 88135
2020-04-01 10:33:15,369 django.server INFO     "GET /register/ HTTP/1.1" 200 2476
2020-04-01 10:34:58,961 django.server INFO     "POST /register/ HTTP/1.1" 302 0
2020-04-01 10:34:58,978 django.server INFO     "GET /accounts/login HTTP/1.1" 301 0
2020-04-01 10:34:59,009 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 814
2020-04-01 10:35:04,440 django.server INFO     "POST /accounts/login/ HTTP/1.1" 302 0
2020-04-01 10:35:04,465 django.request WARNING  Not Found: /
2020-04-01 10:35:04,466 django.server WARNING  "GET / HTTP/1.1" 404 2252
2020-04-01 10:35:12,624 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 814
2020-04-01 10:53:37,289 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_rate\urls.py changed, reloading.
2020-04-01 10:53:40,350 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 10:53:42,430 django.request WARNING  Not Found: /
2020-04-01 10:53:42,431 django.server WARNING  "GET / HTTP/1.1" 404 2261
2020-04-01 10:53:51,986 django.server INFO     "GET /accounts/register HTTP/1.1" 301 0
2020-04-01 10:53:52,030 django.server INFO     "GET /accounts/register/ HTTP/1.1" 200 2485
2020-04-01 11:17:35,411 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 751
2020-04-01 11:17:41,787 django.server INFO     "POST /accounts/login/ HTTP/1.1" 200 840
2020-04-01 11:26:18,718 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_rate\settings.py changed, reloading.
2020-04-01 12:03:58,423 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:14:15,907 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:14:17,231 django.request WARNING  Not Found: /
2020-04-01 12:14:17,232 django.server WARNING  "GET / HTTP/1.1" 404 2261
2020-04-01 12:16:19,163 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_rate\urls.py changed, reloading.
2020-04-01 12:16:20,286 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:16:45,347 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:17:01,558 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\urls.py changed, reloading.
2020-04-01 12:17:02,590 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:17:36,225 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\urls.py changed, reloading.
2020-04-01 12:17:37,270 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:18:06,866 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\urls.py changed, reloading.
2020-04-01 12:18:07,921 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:18:10,939 django.server INFO     "GET / HTTP/1.1" 200 310
2020-04-01 12:18:28,681 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:18:29,772 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:19:15,878 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:19:17,008 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:19:57,429 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:19:58,467 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:20:01,481 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:20:02,610 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:20:12,236 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:20:13,225 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:20:15,110 django.server INFO     "GET / HTTP/1.1" 200 310
2020-04-01 12:20:25,857 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:20:28,084 django.server INFO     "GET / HTTP/1.1" 200 310
2020-04-01 12:23:17,497 django.server INFO     "GET /accounts/logout HTTP/1.1" 301 0
2020-04-01 12:23:17,562 django.server INFO     "GET /accounts/logout/ HTTP/1.1" 200 84
2020-04-01 12:23:22,289 django.server INFO     "GET / HTTP/1.1" 302 0
2020-04-01 12:23:22,312 django.server INFO     "GET /accounts/login/?next=/ HTTP/1.1" 200 809
2020-04-01 12:27:57,122 django.server INFO     "POST /accounts/login/ HTTP/1.1" 302 0
2020-04-01 12:27:57,183 django.server INFO     "GET / HTTP/1.1" 200 374
2020-04-01 12:28:23,453 django.server INFO     "POST /accounts/login/ HTTP/1.1" 200 824
2020-04-01 12:28:37,453 django.server INFO     "POST /accounts/login/ HTTP/1.1" 302 0
2020-04-01 12:28:37,528 django.server INFO     "GET / HTTP/1.1" 200 374
2020-04-01 12:31:34,129 django.server INFO     "GET / HTTP/1.1" 200 359
2020-04-01 12:31:36,965 django.server INFO     "POST / HTTP/1.1" 200 414
2020-04-01 12:37:22,189 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:37:23,252 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:39:30,374 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:39:31,592 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:40:21,337 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:40:22,557 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:40:27,454 django.server INFO     "GET / HTTP/1.1" 200 501
2020-04-01 12:40:35,581 django.request ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py", line 15, in analyze_content
    service = AnalyzerService(form.url_input,form.target_query)
AttributeError: 'AnalyzeForm' object has no attribute 'url_input'
2020-04-01 12:40:35,584 django.server ERROR    "POST / HTTP/1.1" 500 81039
2020-04-01 12:41:13,794 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:41:15,039 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:41:19,376 django.request ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py", line 15, in analyze_content
    url = form.url_input
AttributeError: 'AnalyzeForm' object has no attribute 'url_input'
2020-04-01 12:41:19,378 django.server ERROR    "POST / HTTP/1.1" 500 81076
2020-04-01 12:42:31,184 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:42:32,423 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:42:38,310 django.server INFO     "GET /accounts/logout/ HTTP/1.1" 200 84
2020-04-01 12:42:40,385 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 751
2020-04-01 12:42:41,129 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 751
2020-04-01 12:42:42,798 django.server INFO     "POST /accounts/login/ HTTP/1.1" 302 0
2020-04-01 12:42:42,882 django.server INFO     "GET / HTTP/1.1" 200 501
2020-04-01 12:42:46,038 django.request ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py", line 15, in analyze_content
    url = form.cleaned_data['url_input']
AttributeError: 'AnalyzeForm' object has no attribute 'cleaned_data'
2020-04-01 12:42:46,042 django.server ERROR    "POST / HTTP/1.1" 500 81164
2020-04-01 12:44:37,010 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py changed, reloading.
2020-04-01 12:44:38,240 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:45:07,374 django.request ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py", line 23, in analyze_content
    first_res = service.compare_len()
  File "C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\service\analyzer_service.py", line 25, in compare_len
    sum += len(content.split(" "))
AttributeError: 'Content' object has no attribute 'split'
2020-04-01 12:45:07,377 django.server ERROR    "POST / HTTP/1.1" 500 86656
2020-04-01 12:45:18,115 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\service\analyzer_service.py changed, reloading.
2020-04-01 12:45:25,470 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:45:33,018 django.server INFO     "GET / HTTP/1.1" 200 501
2020-04-01 12:45:47,633 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:46:03,389 django.server INFO     "GET / HTTP/1.1" 200 501
2020-04-01 12:46:22,695 django.request ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\views.py", line 23, in analyze_content
    first_res = service.compare_len()
  File "C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\service\analyzer_service.py", line 25, in compare_len
    sum += len(content.split(" "))
AttributeError: 'Content' object has no attribute 'split'
2020-04-01 12:46:22,697 django.server ERROR    "POST / HTTP/1.1" 500 90282
2020-04-01 12:46:22,699 django.server ERROR    "POST / HTTP/1.1" 500 59
2020-04-01 12:47:56,013 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:48:04,950 django.utils.autoreload INFO     C:\Users\Dan\PycharmProjects\content_rate\content_analyzer\service\analyzer_service.py changed, reloading.
2020-04-01 12:48:06,153 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 12:48:10,475 django.server INFO     "GET / HTTP/1.1" 200 501
2020-04-01 12:48:57,586 django.server INFO     "POST / HTTP/1.1" 200 573
