2020-04-01 08:49:12,585 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-04-01 08:49:25,498 django.request WARNING  Not Found: /
2020-04-01 08:49:25,498 django.server WARNING  "GET / HTTP/1.1" 404 2252
2020-04-01 08:49:29,267 django.request WARNING  Not Found: /
2020-04-01 08:49:29,267 django.server WARNING  "GET / HTTP/1.1" 404 2252
2020-04-01 08:49:29,568 django.request WARNING  Not Found: /login/
2020-04-01 08:49:29,568 django.server WARNING  "GET /login/ HTTP/1.1" 404 2288
2020-04-01 08:49:30,157 django.request WARNING  Not Found: /login/
2020-04-01 08:49:30,157 django.server WARNING  "GET /login/ HTTP/1.1" 404 2288
2020-04-01 08:50:04,893 django.request WARNING  Not Found: /
2020-04-01 08:50:04,894 django.server WARNING  "GET / HTTP/1.1" 404 2252
2020-04-01 08:50:09,495 django.request WARNING  Not Found: /
2020-04-01 08:50:09,495 django.server WARNING  "GET / HTTP/1.1" 404 2252
2020-04-01 08:50:10,007 django.server INFO     "GET /register/ HTTP/1.1" 200 2476
2020-04-01 08:50:11,698 django.server INFO     "GET /register/ HTTP/1.1" 200 2476
2020-04-01 08:50:31,084 django.server INFO     "GET /register/ HTTP/1.1" 200 2476
2020-04-01 08:50:32,579 django.request WARNING  Not Found: /
2020-04-01 08:50:32,580 django.server WARNING  "GET / HTTP/1.1" 404 2252
2020-04-01 08:50:32,876 django.request WARNING  Not Found: /login/
2020-04-01 08:50:32,876 django.server WARNING  "GET /login/ HTTP/1.1" 404 2288
2020-04-01 08:50:34,191 django.request WARNING  Not Found: /login/
2020-04-01 08:50:34,191 django.server WARNING  "GET /login/ HTTP/1.1" 404 2288
2020-04-01 08:51:47,915 django.request WARNING  Not Found: /login/
2020-04-01 08:51:47,915 django.server WARNING  "GET /login/ HTTP/1.1" 404 2288
2020-04-01 08:51:48,660 django.request WARNING  Not Found: /
2020-04-01 08:51:48,660 django.server WARNING  "GET / HTTP/1.1" 404 2252
2020-04-01 08:51:51,391 django.server INFO     "GET /accounts/login HTTP/1.1" 301 0
2020-04-01 08:51:51,402 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 814
2020-04-01 08:51:51,519 django.request WARNING  Not Found: /favicon.ico
2020-04-01 08:51:51,519 django.server WARNING  "GET /favicon.ico HTTP/1.1" 404 2303
2020-04-01 09:01:06,474 django.request ERROR    Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register' not found. 'register' is not a valid view function or pattern name.
2020-04-01 09:01:06,477 django.server ERROR    "GET /accounts/login/ HTTP/1.1" 500 142367
2020-04-01 09:01:34,427 django.request ERROR    Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'register/' not found. 'register/' is not a valid view function or pattern name.
2020-04-01 09:01:34,429 django.server ERROR    "GET /accounts/login/ HTTP/1.1" 500 142388
2020-04-01 09:02:13,442 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 4019
2020-04-01 09:02:19,084 django.server INFO     "GET /register/ HTTP/1.1" 200 2476
2020-04-01 09:03:32,491 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 4062
2020-04-01 09:05:15,194 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 4104
2020-04-01 09:06:43,874 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 3407
2020-04-01 09:07:55,244 django.server INFO     "GET /register/ HTTP/1.1" 200 2476
2020-04-01 09:08:08,779 django.server INFO     "POST /register/ HTTP/1.1" 302 0
2020-04-01 09:08:08,783 django.server INFO     "GET /accounts/login HTTP/1.1" 301 0
2020-04-01 09:08:08,796 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 3407
2020-04-01 09:08:14,116 django.server INFO     "POST /accounts/login/ HTTP/1.1" 302 0
2020-04-01 09:08:14,121 django.request WARNING  Not Found: /
2020-04-01 09:08:14,121 django.server WARNING  "GET / HTTP/1.1" 404 2252
2020-04-01 09:21:24,600 django.server INFO     "GET /register/ HTTP/1.1" 200 4213
2020-04-01 09:23:01,248 django.server INFO     "GET /register/ HTTP/1.1" 200 5984
2020-04-01 09:23:41,697 django.server INFO     "GET /register/ HTTP/1.1" 200 6093
2020-04-01 09:24:02,785 django.server INFO     "GET /register/ HTTP/1.1" 200 6118
2020-04-01 09:24:03,941 django.server INFO     "GET /register/ HTTP/1.1" 200 6118
2020-04-01 09:24:05,367 django.server INFO     "GET /register/ HTTP/1.1" 200 6118
2020-04-01 09:24:11,759 django.server INFO     "GET /register/ HTTP/1.1" 200 6118
2020-04-01 09:25:13,841 django.server INFO     "GET /register/ HTTP/1.1" 200 6210
2020-04-01 09:26:53,679 django.server INFO     "GET /register/ HTTP/1.1" 200 3770
2020-04-01 09:26:55,876 django.server INFO     "GET /register/ HTTP/1.1" 200 3770
2020-04-01 09:27:32,937 django.server INFO     "POST /register/ HTTP/1.1" 200 3918
2020-04-01 09:27:38,573 django.server INFO     "GET /accounts/login/ HTTP/1.1" 200 3407
2020-04-01 09:27:43,296 django.server INFO     "POST /accounts/login/ HTTP/1.1" 302 0
2020-04-01 09:27:43,302 django.request WARNING  Not Found: /
2020-04-01 09:27:43,303 django.server WARNING  "GET / HTTP/1.1" 404 2252
